baseURL = 'https://samoro.st/'
title = 'Samorost'

language = 'cs'
languageCode = 'cs'
defaultContentLanguage = "cs"
[languages]
  [languages.cs]
    disabled = false
    languageCode = 'cs'
    weight = 1
  [languages.en]
    languageCode = 'en'
    weight = 2

[params]
  owner = 'Jan Doskočil'

[taxonomies]
  tag = "tags"

[mediaTypes]
    [mediaTypes."text/x-php"]
        suffixes = ["php"]

[outputFormats]
    [outputFormats.php]
        baseName = "index"
        isPlainText = false
        mediaType = "text/x-php"

[outputs]
  home = ['php']
  page = ['php']
  term = ['php']
  taxonomy = ['php']
  section = ['php']

[privacy]
  [privacy.youTube]
    privacyEnhanced = true

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
    [markup.goldmark.extensions]
      [markup.goldmark.extensions.passthrough]
        enable = true
        [markup.goldmark.extensions.passthrough.delimiters]
          block = [['\[', '\]'], ['$$', '$$']]
          inline = [['\(', '\)']]
      [markup.goldmark.extensions.extras]
        [markup.goldmark.extensions.extras.insert]
          enable = true
        [markup.goldmark.extensions.extras.subscript]
          enable = true
        [markup.goldmark.extensions.extras.mark]
          enable = true
        [markup.goldmark.extensions.extras.superscript]
          enable = true
  [markup.highlight]
    anchorLineNos = false
    codeFences = true
    lineNos = true
    lineNumbersInTable = true
    noClasses = true
    style = 'native'
    tabWidth = 4
    wrapperClass = 'code-highlight'
