SET client_encoding = 'UTF8';

CREATE TABLE posts (
    uid character(32) PRIMARY KEY,
    comments_enabled boolean
);

CREATE TABLE comments (
    uid integer PRIMARY KEY,
    post_id character(32) REFERENCES posts(uid) NOT NULL,
    author character varying(64) NOT NULL,
    title character varying(128) NOT NULL,
    content character varying(10000) NOT NULL,
    date timestamp without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT content_non_empty CHECK ((TRIM(BOTH FROM content) <> ''::text))
);

ALTER TABLE comments ALTER COLUMN uid ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME comments_uid_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);
